item: "diamond"

permission:
  enabled: false
  name: "backpack.use"

messages:
  item_disabled: "§cThis item cannot be placed in a backpack."
  backpack_dropped: "§aYour backpack has been dropped on the ground because your inventory is full!"

item_configuration:
  display_name: "Backpack"
  lore_empty: "§r§9Empty§r"
  lore_content: "§r§9 {item} §6x{count}§r"
  display_name_after_use: "§r§f{player}'s backpack"

ui_configuration:
  display_name: "{player}'s backpack"